name: Jordon Phillips
markdown: redcarpet
pygments: true
safe: true
future: false
lsi: true

paginate: 5
paginate_path: "page:num"

title: Jordon Phillips
description: The humble blog of Jordon Phillips
category: programming
copyright: Copyright (c) 2013 Jordon Phillips. All rights reserved.
production_url: jordonphillips.com

author_name: Jordon Phillips